/* Proposition de modèle éditorial. Ce fichier n'est pas un export importable ACF. */
const field = (label, name, type, required, note, extra = {}) => ({ label, name, type, required, note, ...extra });
const f = field;
const relation = (label, name, targets, multiple = false, note = '', required = false) => f(label, name, multiple ? 'Relation' : 'Objet publication', required, note || (multiple ? 'Sélection de fiches existantes ; retour des identifiants.' : 'Sélection d’une fiche existante ; retour de son identifiant.'), { targets, multiple });
const repeat = (label, name, children, note = '') => f(label, name, 'Répéteur PRO', false, note || 'Ajouter autant de lignes que nécessaire.', { children });
const select = (label, name, choices, required = true, note = '') => f(label, name, 'Sélection', required, note, { choices });
const phone = (name = 'telephone_public') => f('Téléphone public', name, 'Texte', false, 'Format international conseillé ; conserver les signes + et les espaces.');
const email = (name = 'courriel_public') => f('Courriel public', name, 'E-mail', false, 'Adresse professionnelle ou institutionnelle destinée au public.');
const date = (label, name, required = false, note = '') => f(label, name, 'Date', required, note || 'Affichage français ; valeur de retour Y-m-d.');
const datetime = (label, name, required = true) => f(label, name, 'Date et heure', required, 'Fuseau horaire WordPress du site ; retour Y-m-d H:i:s.');
const text = (label, name, required = false, note = '') => f(label, name, 'Texte', required, note);
const area = (label, name, required = false, note = '') => f(label, name, 'Zone de texte', required, note);
const number = (label, name, required = false, note = '') => f(label, name, 'Nombre', required, note);
const url = (label, name, note = '') => f(label, name, 'URL', false, note || 'Adresse complète commençant par https://.');
const docs = (label = 'Documents associés', name = 'documents_associes') => relation(label, name, ['ck_document'], true, 'Réutiliser les documents de la bibliothèque ; ne pas téléverser un second exemplaire.');
const order = () => number('Ordre d’affichage', 'ordre_affichage', false, 'Entier positif ou nul ; valeur proposée : 0.');
const schema = {
  version: '1.0', date: '4 octobre 2026', status: 'Proposition à valider',
  common: {
    id: 'commun', title: 'Source et vérification', group: 'group_ck_verification',
    description: 'Un groupe commun aux 11 types de contenus, avec les mêmes champs et les mêmes règles de saisie.',
    fields: [text('Source de l’information', 'ck_source', false, 'Service municipal, acte ou référence ayant confirmé l’information.'), url('Lien vers la source', 'ck_source_url'), date('Dernière vérification', 'ck_verifie_le', true, 'Date de contrôle humain, distincte de la dernière sauvegarde WordPress.'), date('Prochaine révision souhaitée', 'ck_revision_le', false, 'Repère éditorial ; aucune relance automatique n’est créée par le JSON.')]
  },
  contents: [
    { id:'ck_elu', title:'Élus municipaux', singular:'Élu municipal', family:'Gouvernance', slug:'elus', group:'group_ck_elu', description:'Une fiche par élu, réutilisée pour le conseil municipal, le bureau et la présentation du maire.', native:'Titre : nom et prénom · Contenu : biographie · Image à la une : portrait officiel', taxonomy:[], rules:['Le maire et ses adjoints sont des élus, sans second type de contenu.','Les commissions et les rôles sont renseignés dans la composition des commissions. Leur affichage sur la fiche de l’élu sera calculé à partir de cette relation.'], fields:[
      select('Fonction municipale','fonction',['Maire','Premier adjoint','Deuxième adjoint','Troisième adjoint','Quatrième adjoint','Conseiller municipal','Conseillère municipale']),
      text('Intitulé public complémentaire','qualite_publique',false,'Précision éventuelle sur la qualité ou la délégation.'), date('Début du mandat','mandat_debut',true),date('Fin du mandat','mandat_fin',false,'À renseigner lorsqu’elle est connue ; doit être postérieure au début.'), area('Délégations et attributions','delegations'),area('Présentation courte','presentation_courte',false,'Environ 300 caractères pour les listes et cartes.'),area('Permanences et rendez-vous','permanences',false,'Informations pratiques ; aucune réservation en ligne.'),phone(),email(),text('Crédit du portrait','credit_photo'),f('Publication du portrait autorisée','photo_autorisee','Vrai / Faux',false,'Valeur initiale : non ; confirmer avant publication du portrait.'),order()
    ]},
    { id:'ck_agent', title:'Agents et responsables', singular:'Agent ou responsable', family:'Institution', slug:'administration-municipale', group:'group_ck_agent', description:'L’annuaire professionnel public de l’administration municipale.', native:'Titre : nom et prénom · Contenu : présentation professionnelle · Image : portrait autorisé',taxonomy:[],rules:['Uniquement les informations professionnelles destinées au public.','Le lien vers un responsable hiérarchique ne doit pas former de boucle ; ce contrôle demandera une validation complémentaire.'],fields:[
      text('Fonction','fonction',true),relation('Service de rattachement','service',['ck_service'],false,'Unité dans laquelle travaille l’agent.',true),relation('Responsable hiérarchique','responsable_hierarchique',['ck_agent'],false,'Facultatif ; jamais l’agent lui-même.'),area('Missions publiques','missions'),phone(),email(),text('Bureau ou lieu d’accueil','bureau'),area('Disponibilités publiques','disponibilites'),text('Crédit du portrait','credit_photo'),f('Publication du portrait autorisée','photo_autorisee','Vrai / Faux',false,'Valeur initiale : non.'),order()
    ]},
    { id:'ck_service', title:'Services municipaux', singular:'Service municipal', family:'Institution', slug:'services-municipaux', group:'group_ck_service', description:'Les unités de la mairie, leurs missions et leurs contacts.', native:'Titre : nom du service · Contenu : présentation · Service parent : attribut natif WordPress',taxonomy:['ck_theme'],rules:['Hiérarchie activée : une division peut dépendre d’un autre service.','Le responsable est sélectionné parmi les agents ; il n’est pas ressaisi sous forme de texte.'],fields:[
      area('Missions','missions',true),relation('Responsable public','responsable',['ck_agent']),area('Adresse et accès','adresse',true),phone(),email(),repeat('Horaires d’accueil','horaires',[select('Jour','jour',['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche']),f('Ouverture','ouverture','Heure',true,'Format H:i.'),f('Fermeture','fermeture','Heure',true,'Format H:i.')],'Plusieurs lignes possibles pour un même jour en cas de pause méridienne.'),area('Modalités d’accueil','modalites_accueil',false,'Accueil libre, rendez-vous par téléphone ou autres indications confirmées.'),url('Plan d’accès','plan_url'),order()
    ]},
    { id:'ck_demarche', title:'Démarches administratives', singular:'Démarche administrative', family:'Services et information', slug:'demarches', group:'group_ck_demarche',description:'Des fiches pratiques pour préparer une démarche auprès de la mairie.',native:'Titre : action recherchée, par exemple « Obtenir un extrait de naissance » · Contenu : explications complémentaires',taxonomy:['ck_theme','ck_famille_demarche'],rules:['Catalogue informatif : aucun dépôt de dossier, paiement ou suivi individuel.','Les tarifs et délais restent vides tant qu’ils ne sont pas confirmés ; ne pas confondre absence de montant et gratuité.'],fields:[
      area('Finalité','finalite',true),area('Qui peut demander','beneficiaires',true),area('Conditions préalables','conditions'),repeat('Pièces à préparer','pieces',[text('Pièce demandée','intitule',true),select('Présentation','format',['À préciser','Original','Copie','Original et copie'],false),area('Précisions','precisions')]),select('Nature du coût','nature_cout',['À confirmer','Gratuit','Montant fixe','Coût variable']),number('Montant en FCFA','montant_fcfa',false,'Entier ≥ 0 ; visible et obligatoire si « Montant fixe ».',{ }),area('Précisions tarifaires','precisions_tarifaires',false,'Base de calcul si coût variable.'),text('Délai annoncé','delai',false,'Exemple de format : 3 jours ouvrés ; renseigner la durée validée.'),select('Nature du délai','nature_delai',['À confirmer','Indicatif','Réglementaire'],false),repeat('Étapes de la démarche','etapes',[text('Étape','titre',true),area('Explication','description',true)]),area('Résultat délivré','resultat',true),text('Durée de validité','validite'),f('Canaux disponibles','canaux','Cases à cocher',true,'Information sur les modes d’accueil.',{choices:['Au guichet','Sur rendez-vous','Service mobile ou forain']}),relation('Service compétent','service',['ck_service'],false,'Service municipal chargé de la démarche.',true),area('Recours ou réclamation','recours'),docs()
    ]},
    { id:'ck_commission',title:'Commissions municipales',singular:'Commission municipale',family:'Gouvernance',slug:'commissions',group:'group_ck_commission',description:'Les compétences et la composition de chaque commission du conseil.',native:'Titre : nom officiel · Contenu : présentation',taxonomy:['ck_theme'],rules:['La composition constitue la source unique des appartenances aux commissions.','Les fonctions dont les titulaires ne sont pas confirmés restent à renseigner ; aucun nom ne sera inventé.'],fields:[
      area('Compétences','competences',true),date('Début du mandat','mandat_debut'),date('Fin du mandat','mandat_fin'),repeat('Composition','composition',[relation('Élu','elu',['ck_elu'],false,'Choisir un élu existant.',true),select('Rôle','role',['Président','Présidente','Vice-président','Vice-présidente','Rapporteur','Rapporteuse','Membre']),text('Précision de fonction','precision')],'Une ligne par élu ; vérifier les doublons et l’attribution des fonctions.'),area('Travaux publics','travaux_publics'),docs('Rapports et documents publics','documents_associes'),order()
    ]},
    { id:'ck_session',title:'Sessions du conseil',singular:'Session du conseil',family:'Gouvernance',slug:'sessions-du-conseil',group:'group_ck_session',description:'Les séances du conseil, de leur annonce à la publication des décisions.',native:'Titre : intitulé de la session · Contenu : présentation ou compte rendu éditorial',taxonomy:[],rules:['Les délibérations sont des Documents publics liés à la session ; la liste sera dérivée de ce lien.','L’agenda pourra reprendre les sessions sans créer un événement identique.'],fields:[
      datetime('Date et heure','date_heure'),text('Lieu','lieu',true),select('Type de session','type_session',['Ordinaire','Extraordinaire']),select('Statut','statut',['Annoncée','Tenue','Reportée','Annulée']),repeat('Ordre du jour','ordre_du_jour',[text('Point à examiner','objet',true),area('Précision','precision')]),area('Conditions d’accès public','acces_public'),relation('Procès-verbal communicable','proces_verbal',['ck_document']),area('Compte rendu synthétique','compte_rendu'),docs('Documents préparatoires communicables','documents_preparatoires')
    ]},
    { id:'ck_projet',title:'Projets municipaux',singular:'Projet municipal',family:'Action publique',slug:'projets-municipaux',group:'group_ck_projet',description:'Le suivi public des réalisations et investissements de la commune.',native:'Titre : nom du projet · Contenu : présentation détaillée · Image : photographie principale',taxonomy:['ck_theme','ck_zone'],rules:['L’avancement repose sur des jalons et des informations vérifiées, sans pourcentage arbitraire.','Les coordonnées géographiques sont facultatives ; le village ou la zone suffit à localiser un projet.'],fields:[
      text('Référence publique','reference'),area('Besoin traité','besoin',true),area('Objectifs','objectifs',true),area('Bénéficiaires','beneficiaires',false,'Description ou effectif agrégé.'),relation('Service porteur','service',['ck_service']),select('Statut','statut',['Prévu','En préparation','En cours','Suspendu','Achevé']),text('Localisation précise','localisation'),number('Latitude','latitude',false,'Entre −90 et 90.'),number('Longitude','longitude',false,'Entre −180 et 180.'),number('Budget publiable en FCFA','budget_fcfa',false,'Entier ≥ 0 ; vide signifie non renseigné.'),number('Part communale en FCFA','part_communale_fcfa',false,'Entier ≥ 0 ; ne doit pas dépasser le budget total renseigné.'),repeat('Financeurs et partenaires','partenaires',[text('Organisme','nom',true),text('Rôle ou contribution','contribution'),url('Site officiel','url')]),date('Lancement','date_lancement'),date('Échéance prévue','date_echeance'),repeat('Jalons','jalons',[text('Étape','titre',true),date('Date prévue','date_prevue'),date('Date réalisée','date_realisee'),select('État','etat',['À venir','En cours','Réalisé','Reporté'])]),area('Prochaine étape publique','prochaine_etape'),area('Résultats obtenus','resultats'),repeat('Indicateurs','indicateurs',[text('Indicateur','nom',true),text('Valeur de départ','avant'),text('Valeur obtenue','apres'),text('Unité','unite'),date('Date de mesure','mesure_le')]),date('Mise en service','date_mise_service'),f('Galerie du projet','galerie','Galerie PRO',false,'Images optimisées et légendes datées ; retour des identifiants des médias.')
    ]},
    { id:'ck_document',title:'Documents publics',singular:'Document public',family:'Transparence',slug:'documents-publics',group:'group_ck_document',description:'La bibliothèque officielle : actes, délibérations, budgets et rapports communicables.',native:'Titre : objet du document · Contenu : résumé éditorial complémentaire',taxonomy:['ck_theme','ck_zone','ck_type_document'],rules:['Les fichiers officiels sont conservés tels quels ; le résumé éditorial reste distinct.','Un document est téléversé une seule fois puis relié aux dossiers concernés.','Le statut natif Brouillon / Publié contrôle sa diffusion ; seuls les fichiers communicables ont vocation à être téléversés.'],fields:[
      text('Numéro ou référence','reference'),date('Date du document','date_document',true),text('Émetteur ou signataire institutionnel','emetteur',true),area('Résumé','resume',true),f('Fichier officiel','fichier','Fichier',true,'PDF par défaut ; retour ID, utilisé pour déterminer le lien, le format et le poids.'),number('Année de référence','annee_reference',false,'Année à quatre chiffres, utile notamment pour les budgets.'),text('Version','version',false,'Exemple : version adoptée ; ne pas reconstituer un historique non disponible.'),relation('Session liée','session',['ck_session']),relation('Projet lié','projet',['ck_projet']),relation('Document remplacé','document_remplace',['ck_document'],false,'Facultatif ; lien vers une version antérieure conservée.')
    ]},
    { id:'ck_marche',title:'Marchés publics',singular:'Marché public',family:'Transparence',slug:'marches-publics',group:'group_ck_marche',description:'Les avis et les résultats publics des procédures de la commune.',native:'Titre : objet du marché · Contenu : présentation',taxonomy:['ck_theme','ck_zone'],rules:['Une fiche regroupe les avis, le dossier et les résultats d’une même procédure.','Le dépôt des offres ne se fait pas sur ce portail ; les modalités indiquent le canal officiel.'],fields:[
      text('Référence','reference',true),area('Objet','objet',true),text('Procédure','procedure',true,'Intitulé officiel validé par le service compétent.'),relation('Service compétent','service',['ck_service']),date('Date de publication de l’avis','date_publication',true),datetime('Date et heure limites','date_limite'),select('Statut','statut',['Annoncé','Ouvert','Clôturé','Attribué','Annulé']),area('Modalités de retrait du dossier','retrait_dossier'),area('Modalités de dépôt','modalites_depot'),docs('Avis et dossier public','documents_dossier'),area('Résultats publiables','resultats'),docs('Documents d’attribution','documents_attribution'),phone(),email()
    ]},
    { id:'ck_alerte',title:'Alertes',singular:'Alerte',family:'Communication',slug:'alertes-municipales',group:'group_ck_alerte',description:'Des consignes officielles prioritaires et limitées dans le temps.',native:'Titre : message bref · Contenu : explications complémentaires',taxonomy:['ck_theme','ck_zone'],rules:['Les champs décrivent la période d’activation ; le bandeau et son expiration seront intégrés ensuite.','Une zone vide signifie toute la commune ; une alerte doit toujours afficher sa source.'],fields:[
      select('Niveau','niveau',['Information','Vigilance','Urgence']),area('Consigne principale','consigne',true,'Message court et actionnable.'),datetime('Début de validité','debut'),datetime('Fin de validité','fin'),text('Source publique','source_publique',true),f('Afficher dans le bandeau','afficher_bandeau','Vrai / Faux',false,'Valeur proposée : non. Ne rend pas la fiche visible tant qu’elle est en brouillon.'),f('Bouton d’action','action','Lien',false,'Libellé, URL et cible ; facultatif.')
    ]},
    { id:'ck_evenement',title:'Événements institutionnels',singular:'Événement institutionnel',family:'Communication',slug:'agenda-institutionnel',group:'group_ck_evenement',description:'Les réunions publiques, cérémonies et opérations municipales.',native:'Titre : nom de l’événement · Contenu : présentation · Image : visuel officiel',taxonomy:['ck_theme','ck_zone','ck_categorie_evenement'],rules:['L’agenda institutionnel pourra réunir ces événements et les sessions du conseil.','Aucune billetterie ni réservation n’est prévue.'],fields:[
      datetime('Début','debut'),datetime('Fin','fin',false),f('Toute la journée','toute_journee','Vrai / Faux',false,'Valeur initiale : non ; masquer les heures à l’affichage si activé.'),select('Statut','statut',['Programmé','Reporté','Annulé','Terminé']),text('Lieu','lieu',true),area('Adresse et accès','adresse'),text('Organisateur','organisateur',true),relation('Service organisateur','service',['ck_service']),area('Conditions d’accès','conditions_acces'),phone(),email(),url('Lien d’information','lien_information'),docs()
    ]}
  ],
  taxonomies: [
    {id:'ck_theme',title:'Thématiques',singular:'Thématique',hierarchical:true,description:'Un classement transversal pour retrouver les informations par sujet.',terms:['Administration générale','État civil','Foncier et urbanisme','Finances et transparence','Éducation et formation','Santé et action sociale','Environnement et assainissement','Voirie et réseaux','Jeunesse, sport et culture','Développement communal'],note:'Liste de départ proposée, à valider avec la mairie ; les sous-thèmes pourront être ajoutés.'},
    {id:'ck_zone',title:'Villages et zones',singular:'Village ou zone',hierarchical:true,description:'La localisation administrative des actions et informations publiques.',terms:['Abéné','Albadar','Diannah','Kafountine','Kolomba','Couba','Coumbaloulou','Hillol','Boune','Boko','Saloulou','Bakassouk','Diogué/Dioogué','Kassel','Mantate','Kaïlo','Haer / Haère','Hitou','Niomoune'],note:'Les 19 villages proviennent de la liste publiée par la Commune de Kafountine. Aucun contenu touristique n’est créé dans le portail institutionnel.'},
    {id:'ck_famille_demarche',title:'Familles de démarches',singular:'Famille de démarches',hierarchical:true,description:'Les rubriques du catalogue pratique destiné aux habitants.',terms:['Administration générale','État civil','Foncier','Urbanisme et travaux','Domaine public','Taxes et redevances','Hygiène et salubrité','Action sociale','Éducation et formation','Jeunesse, sport et culture','Voirie et cadre de vie','Entreprises et marchés publics','Accès à l’information'],note:'Les fiches expliquent les procédures ; elles ne déclenchent aucune demande en ligne.'},
    {id:'ck_type_document',title:'Types de documents',singular:'Type de document',hierarchical:true,description:'La nature officielle du document dans la bibliothèque publique.',terms:['Délibération','Arrêté','Décision','Procès-verbal','Compte rendu','Budget','Compte financier','Rapport','Plan ou programme','Avis public','Convention communicable','Dossier de consultation'],note:'Les délibérations restent dans Documents publics et sont filtrées grâce à cette taxonomie.'},
    {id:'ck_categorie_evenement',title:'Catégories d’événements',singular:'Catégorie d’événement',hierarchical:true,description:'Le classement de l’agenda institutionnel.',terms:['Réunion publique','Cérémonie officielle','Campagne municipale','Opération de terrain','Rencontre institutionnelle'],note:'Les sessions du conseil gardent leur propre type de contenu et alimenteront le même agenda.'}
  ],
  options: [
    {id:'ck_identite',title:'Identité de la commune',group:'group_ck_options_identite',description:'Les éléments institutionnels réutilisés dans l’en-tête, le pied de page et les pages de présentation.',fields:[
      text('Dénomination officielle','denomination',true),f('Logo officiel','logo','Image',false,'Retour ID ; renseigner le texte alternatif dans la médiathèque.'),area('Présentation courte','presentation',true),text('Région','region'),text('Département','departement'),text('Arrondissement','arrondissement'),area('Mentions institutionnelles','mentions'),repeat('Réseaux et canaux officiels','reseaux',[text('Nom du canal','nom',true),f('Adresse du profil','url','URL',true,'Profil officiel validé par la commune.')])
    ]},
    {id:'ck_coordonnees',title:'Coordonnées et horaires',group:'group_ck_options_coordonnees',description:'Les informations de contact communes à tout le portail.',fields:[
      area('Adresse de la mairie','adresse',true),phone(),email(),url('Plan d’accès','plan_url'),repeat('Horaires habituels','horaires',[select('Jour','jour',['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche']),f('Ouverture','ouverture','Heure',true,'Format H:i.'),f('Fermeture','fermeture','Heure',true,'Format H:i.')],'Plusieurs créneaux possibles par jour ; les jours sans créneau sont fermés.'),repeat('Fermetures exceptionnelles','fermetures',[date('Premier jour','debut',true),date('Dernier jour','fin',true),text('Motif public','motif',true)]),repeat('Contacts utiles','contacts_utiles',[text('Service ou organisme','nom',true),phone(),text('Précision','precision')]),area('Modalités d’accueil','modalites_accueil')
    ]},
    {id:'ck_portail',title:'Paramètres du portail',group:'group_ck_options_portail',description:'Les choix éditoriaux globaux et les sélections de la page d’accueil.',fields:[
      relation('Maire en fonction','maire',['ck_elu'],false,'Choisir la fiche existante du maire.',true),date('Début du mandat en cours','mandat_debut',true),date('Fin du mandat en cours','mandat_fin'),text('Titre d’accueil','titre_accueil',true),area('Introduction de l’accueil','introduction_accueil'),repeat('Raccourcis d’accueil','raccourcis',[text('Libellé','libelle',true),f('Destination','lien','Lien',true,'Lien vers une page ou fiche informative du portail.')],'Maximum proposé : 6 raccourcis.'),relation('Projets mis en avant','projets',['ck_projet'],true,'Sélection ordonnée de 3 à 6 projets publiés, si disponibles.'),f('Autoriser le bandeau d’alertes','bandeau_actif','Vrai / Faux',false,'Commutateur global ; l’alerte doit aussi être publiée et dans sa période de validité.'),number('Nombre d’actualités à l’accueil','nombre_actualites',false,'Entier de 1 à 6 ; valeur proposée : 3.'),f('Page des mentions légales','mentions_legales','Objet publication',false,'Sélection d’une page WordPress existante.',{targets:['page']}),f('Page de confidentialité','confidentialite','Objet publication',false,'Sélection d’une page WordPress existante.',{targets:['page']})
    ]}
  ],
  relations: [
    ['ck_agent','ck_service','Service de rattachement','Un agent appartient à un service.'],['ck_agent','ck_agent','Responsable hiérarchique','Une relation vers un autre agent, sans boucle.'],['ck_service','ck_agent','Responsable public','Un service désigne son responsable.'],['ck_service','ck_service','Service parent','Hiérarchie native WordPress.'],['ck_demarche','ck_service','Service compétent','Chaque démarche désigne le bon interlocuteur.'],['ck_commission','ck_elu','Composition et rôles','Les appartenances d’un élu sont déduites de cette composition.'],['ck_document','ck_session','Session liée','Les délibérations d’une session proviennent de ce lien.'],['ck_document','ck_projet','Projet lié','Les documents d’un projet proviennent de ce lien.'],['ck_document','ck_document','Version précédente','La fiche peut désigner le document qu’elle remplace.'],['ck_session','ck_document','PV et pièces préparatoires','Réutilisation des fichiers de la bibliothèque.'],['ck_projet','ck_service','Service porteur','Responsabilité du projet.'],['ck_marche','ck_document','Dossier et résultats','Réutilisation des documents officiels.'],['ck_marche','ck_service','Service compétent','Contact responsable de la procédure.'],['ck_evenement','ck_service','Service organisateur','Rattachement facultatif.'],['ck_portail','ck_elu','Maire en fonction','Réutilisation d’une fiche existante.'],['ck_portail','ck_projet','Sélection de l’accueil','Liste ordonnée des projets mis en avant.']
  ]
};
